name: paystack_manager
description: A Flutter plugin for making payments via Paystack Payment Gateway. Fully supports Android and iOS.
version: 1.0.5
author: Ambrose Bako<bakoambrose@gmail.com>
homepage: https://github.com/ambrosethebuild/paystack_manager.git

plugin:
    platforms:
      android:
        package: com.example.paystack_manager
        pluginClass: PaystackPayManager
      ios:
        pluginClass: PaystackPayManager

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  flutter_icons: ^1.1.0
  dio: ^3.0.10
  pin_code_fields: ^6.1.0
  pinput: ^0.2.2
  webview_flutter: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
